#ifndef __DEFS_H__
#define __DEFS_H__

// SCREEN
#define SCREEN_WIDTH 320
#define SCREEN_HEIGHT 200

// VGA
#define VGA_PLANE_SHIFT 2
#define VGA_PLANE_COUNT (1 << VGA_PLANE_SHIFT)
#define VGA_PAGE_COUNT 4
#define VGA_PLANE_WIDTH (SCREEN_WIDTH / VGA_PLANE_COUNT)
#define VGA_PAGE_SIZE (VGA_PLANE_WIDTH * SCREEN_HEIGHT)

// FNC
#define FNC_UPS_START 0
#define FNC_UPS_RUBY 0
#define FNC_UPS_DIAMOND 1
#define FNC_UPS_GOBLET 2
#define FNC_UPS_CROWN 3
#define FNC_UPS_HEAL 4
#define FNC_UPS_CRYSTAL 5
#define FNC_UPS_HURT 6
#define FNC_UPS_ADD_SHOT 7
#define FNC_UPS_INVISIBLE 8
#define FNC_UPS_SUPER_JUMP 9
#define FNC_UPS_SUPER_SHOT 10
#define FNC_UPS_SMART_BOMB 11
#define FNC_UPS_SILVER_KEY 12
#define FNC_UPS_GOLD_KEY 13
#define FNC_UPS_KILL 14
#define FNC_UPS_WIZARD_NOTE 15
#define FNC_UPS_LASER_SHOT 16
#define FNC_UPS_END 22
#define FNC_WARPS_START 23
#define FNC_WARPS_END 32
#define FNC_SWITCHES_START 33
#define FNC_SWITCHES_END 55
#define FNC_RTRIPS_START 56
#define FNC_RTRIPS_END 80
#define FNC_ETRIPS_START 81
#define FNC_ETRIPS_END 105
#define FNC_SPRITES_START 106
#define FNC_SPRITES_END 115
#define FNC_MTRIGGERS_START 116
#define FNC_MTRIGGERS_END 365
#define FNC_NONE 30000

// COUNTS
#define UPS_COUNT (FNC_UPS_END - FNC_UPS_START + 1)
#define WARPS_COUNT (FNC_WARPS_END - FNC_WARPS_START + 1)
#define SWITCHES_COUNT (FNC_SWITCHES_END - FNC_SWITCHES_START + 1)
#define RTRIPS_COUNT (FNC_RTRIPS_END - FNC_RTRIPS_START + 1)
#define ETRIPS_COUNT (FNC_ETRIPS_END - FNC_ETRIPS_START + 1)
#define SPRITES_COUNT (FNC_SPRITES_END - FNC_SPRITES_START + 1)
#define MTRIGGERS_COUNT (FNC_MTRIGGERS_END - FNC_MTRIGGERS_START + 1)
#define MTAGS_COUNT SPRITES_COUNT
#define GAME_COUNT 4
#define LEVEL_COUNT 9
#define STORY_COUNT 10
#define DEMO_COUNT 5

#if VERSION_PROTO
#define CREDIT_COUNT 8
#define PREVIEW_COUNT 10
#define ORDER_COUNT 22
#else
#define CREDIT_COUNT 2
#define PREVIEW_COUNT 11
#define ORDER_COUNT 10
#endif

#if VERSION_11 || VERSION_DEMO11
#define HELP_COUNT 5
#else
#define HELP_COUNT 4
#endif

#if VERSION_10 || VERSION_11
#define EPISODE_COUNT 4
#define MUSIC_COUNT 12
#else
#define EPISODE_COUNT 1
#define MUSIC_COUNT 11
#endif

// OFFSETS
#define OFFSET_FONT 0

#if VERSION_PROTO
#define OFFSET_CONFIG (OFFSET_FONT + 1)
#define OFFSET_APOGEE (OFFSET_CONFIG + 1)
#define OFFSET_TITLE (OFFSET_APOGEE + 1)
#define OFFSET_WARP (OFFSET_TITLE + 1)
#elif VERSION_10 || VERSION_11
#define OFFSET_APOGEE (OFFSET_FONT + 1)
#define OFFSET_TITLE (OFFSET_APOGEE + 1)
#define OFFSET_REGIST (OFFSET_TITLE + 1)
#define OFFSET_WARP (OFFSET_REGIST + 1)
#elif VERSION_DEMO10 || VERSION_DEMO11
#define OFFSET_APOGEE (OFFSET_FONT + 1)
#define OFFSET_TITLE (OFFSET_APOGEE + 1)
#define OFFSET_WARP (OFFSET_TITLE + 1)
#endif

#define OFFSET_SINCOS (OFFSET_WARP + 1)
#define OFFSET_RANDOM (OFFSET_SINCOS + 1)
#define OFFSET_GAMEPAL (OFFSET_RANDOM + 1)
#define OFFSET_MENUPAL (OFFSET_GAMEPAL + 1)
#define OFFSET_BOTTOM (OFFSET_MENUPAL + 1)
#define OFFSET_HOCUS (OFFSET_BOTTOM + 1)
#define OFFSET_HUDSTUFF (OFFSET_HOCUS + 1)
#define OFFSET_NEW_HUD (OFFSET_HUDSTUFF + 1)
#define OFFSET_OLD_HUD (OFFSET_NEW_HUD + 1)
#define OFFSET_BULLIT (OFFSET_OLD_HUD + 1)

#if VERSION_PROTO
#define OFFSET_DEMO (OFFSET_BULLIT + 1)
#elif VERSION_10 || VERSION_11
#define OFFSET_VOL_BAR (OFFSET_BULLIT + 1)
#define OFFSET_CRYSTAL (OFFSET_VOL_BAR + 1)
#define OFFSET_PIRACY (OFFSET_CRYSTAL + 1)
#define OFFSET_DEMO (OFFSET_PIRACY + 1)
#elif VERSION_DEMO10 || VERSION_DEMO11
#define OFFSET_VOL_BAR (OFFSET_BULLIT + 1)
#define OFFSET_CRYSTAL (OFFSET_VOL_BAR + 1)
#define OFFSET_DEMO (OFFSET_CRYSTAL + 1)
#endif

#define OFFSET_CREDIT (OFFSET_DEMO + DEMO_COUNT)
#define OFFSET_HELP (OFFSET_CREDIT + CREDIT_COUNT)
#define OFFSET_PREVIEW (OFFSET_HELP + HELP_COUNT)
#define OFFSET_ORDER (OFFSET_PREVIEW + PREVIEW_COUNT)
#define OFFSET_REGISTER (OFFSET_ORDER + ORDER_COUNT)

#if VERSION_PROTO
#define OFFSET_BACKPAL (OFFSET_REGISTER + 1)
#elif VERSION_10 || VERSION_11
#define OFFSET_STORY (OFFSET_REGISTER + 1)
#define OFFSET_E1END1 (OFFSET_STORY + STORY_COUNT)
#define OFFSET_E1END2 (OFFSET_E1END1 + 1)
#define OFFSET_E2END1 (OFFSET_E1END2 + 1)
#define OFFSET_E2END2 (OFFSET_E2END1 + 1)
#define OFFSET_E3END1 (OFFSET_E2END2 + 1)
#define OFFSET_E3END2 (OFFSET_E3END1 + 1)
#define OFFSET_E3END3 (OFFSET_E3END2 + 1)
#define OFFSET_E3END4 (OFFSET_E3END3 + 1)
#define OFFSET_E4END1 (OFFSET_E3END4 + 1)
#define OFFSET_E4END2 (OFFSET_E4END1 + 1)
#define OFFSET_KISS (OFFSET_E4END2 + 1)
#define OFFSET_BACKPAL (OFFSET_KISS + 1)
#elif VERSION_DEMO10 || VERSION_DEMO11
#define OFFSET_STORY (OFFSET_REGISTER + 1)
#define OFFSET_E1END1 (OFFSET_STORY + STORY_COUNT)
#define OFFSET_E1END2 (OFFSET_E1END1 + 1)
#define OFFSET_BACKPAL (OFFSET_E1END2 + 1)
#endif

#define OFFSET_BACKPCX (OFFSET_BACKPAL + (4 * EPISODE_COUNT))
#define OFFSET_TILE (OFFSET_BACKPCX + (4 * EPISODE_COUNT))

#if VERSION_PROTO
#define OFFSET_WIN (OFFSET_TILE + (4 * EPISODE_COUNT))
#define OFFSET_SPRITES (OFFSET_WIN + 1)
#else
#define OFFSET_PIC1 (OFFSET_TILE + (4 * EPISODE_COUNT))
#define OFFSET_WIN (OFFSET_PIC1 + 1)
#define OFFSET_PIC2 (OFFSET_WIN + 1)
#define OFFSET_PIC3 (OFFSET_PIC2 + 1)
#define OFFSET_PIC4 (OFFSET_PIC3 + 1)
#define OFFSET_PIC5 (OFFSET_PIC4 + 1)
#define OFFSET_PIC6 (OFFSET_PIC5 + 1)
#define OFFSET_PIC7 (OFFSET_PIC6 + 1)
#define OFFSET_PIC8 (OFFSET_PIC7 + 1)
#define OFFSET_SPRITES (OFFSET_PIC8 + 1)
#endif

#define OFFSET_LVLINFO (OFFSET_SPRITES + 1)
#define OFFSET_ANMINFO (OFFSET_LVLINFO + (LEVEL_COUNT * EPISODE_COUNT))
#define OFFSET_WIZNOTES (OFFSET_ANMINFO + (LEVEL_COUNT * EPISODE_COUNT))
#define OFFSET_WARPS (OFFSET_WIZNOTES + (LEVEL_COUNT * EPISODE_COUNT))
#define OFFSET_SWITCHES (OFFSET_WARPS + (LEVEL_COUNT * EPISODE_COUNT))
#define OFFSET_RTRIPS (OFFSET_SWITCHES + (LEVEL_COUNT * EPISODE_COUNT))
#define OFFSET_ETRIPS (OFFSET_RTRIPS + (LEVEL_COUNT * EPISODE_COUNT))
#define OFFSET_MTAGS (OFFSET_ETRIPS + (LEVEL_COUNT * EPISODE_COUNT))
#define OFFSET_MTRIGGERS (OFFSET_MTAGS + (LEVEL_COUNT * EPISODE_COUNT))
#define OFFSET_BKG (OFFSET_MTRIGGERS + (LEVEL_COUNT * EPISODE_COUNT))
#define OFFSET_SLD (OFFSET_BKG + (LEVEL_COUNT * EPISODE_COUNT))
#define OFFSET_SLDSAV (OFFSET_SLD + (LEVEL_COUNT * EPISODE_COUNT))
#define OFFSET_FNC (OFFSET_SLDSAV + (LEVEL_COUNT * EPISODE_COUNT))
#define OFFSET_MUSIC (OFFSET_FNC + (LEVEL_COUNT * EPISODE_COUNT))
#define OFFSET_SOUND (OFFSET_MUSIC + MUSIC_COUNT)

#if VERSION_PROTO
#define OFFSET_DOSMSG (OFFSET_SOUND + 28)
#else
#define OFFSET_DOSSHARE (OFFSET_SOUND + 39)
#define OFFSET_DOSREG (OFFSET_DOSSHARE + 1)
#endif

// MUSIC
#define MUSIC_FANFARE (OFFSET_MUSIC + 0)
#define MUSIC_TITLE (OFFSET_MUSIC + 3)

// KEYS
#define KEY_RETURN 13
#define KEY_ESCAPE 27
#define KEY_SPACE 32
#define KEY_ALT_W 17
#define KEY_ALT_E 18
#define KEY_ALT_R 19
#define KEY_ALT_T 20
#define KEY_ALT_U 22
#define KEY_ALT_S 31
#define KEY_ALT_Z 44
#define KEY_ALT_B 48
#define KEY_ALT_M 50
#define KEY_F1 59
#define KEY_F2 60
#define KEY_F3 61
#define KEY_F4 62
#define KEY_F5 63
#define KEY_F6 64
#define KEY_F7 65
#define KEY_F8 66
#define KEY_F9 67
#define KEY_F10 68
#define KEY_HOME 71
#define KEY_UP 72
#define KEY_PGUP 73
#define KEY_LEFT 75
#define KEY_RIGHT 77
#define KEY_END 79
#define KEY_DOWN 80
#define KEY_PGDN 81
#define KEY_INSERT 82
#define KEY_DELETE 83

#endif