#ifndef __DEFS_H__
#define __DEFS_H__

// SCREEN
#define SCREEN_WIDTH 320
#define SCREEN_HEIGHT 200

// VGA
#define VGA_PLANE_COUNT (1 << VGA_PLANE_SHIFT)
#define VGA_PAGE_COUNT 4
#define VGA_PLANE_WIDTH (SCREEN_WIDTH / VGA_PLANE_COUNT)
#define VGA_PAGE_SIZE (VGA_PLANE_WIDTH * SCREEN_HEIGHT)

// OFFSETS
#define OFFSET_LVLINFO 79
#define OFFSET_ANMINFO (OFFSET_LVLINFO + 9)
#define OFFSET_WIZNOTES (OFFSET_ANMINFO + 9)
#define OFFSET_WARPS (OFFSET_WIZNOTES + 9)
#define OFFSET_SWITCHES (OFFSET_WARPS + 9)
#define OFFSET_RTRIPS (OFFSET_SWITCHES + 9)
#define OFFSET_ETRIPS (OFFSET_RTRIPS + 9)
#define OFFSET_MTAGS (OFFSET_ETRIPS + 9)
#define OFFSET_MTRIGGERS (OFFSET_MTAGS + 9)
#define OFFSET_BKG (OFFSET_MTRIGGERS + 9)
#define OFFSET_SLD (OFFSET_BKG + 9)
#define OFFSET_SLDSAV (OFFSET_SLD + 9)
#define OFFSET_FNC (OFFSET_SLDSAV + 9)

// FNC
#define FNC_UPS_START 0
#define FNC_UPS_RUBY 0
#define FNC_UPS_DIAMOND 1
#define FNC_UPS_GOBLET 2
#define FNC_UPS_CROWN 3
#define FNC_UPS_HEAL 4
#define FNC_UPS_CRYSTAL 5
#define FNC_UPS_HURT 6
#define FNC_UPS_ADD_SHOT 7
#define FNC_UPS_INVISIBLE 8
#define FNC_UPS_SUPER_JUMP 9
#define FNC_UPS_SUPER_SHOT 10
#define FNC_UPS_SMART_BOMB 11
#define FNC_UPS_SILVER_KEY 12
#define FNC_UPS_GOLD_KEY 13
#define FNC_UPS_KILL 14
#define FNC_UPS_WIZARD_NOTE 15
#define FNC_UPS_LASER_SHOT 16
#define FNC_UPS_END 22
#define FNC_WARPS_START 23
#define FNC_WARPS_END 32
#define FNC_SWITCHES_START 33
#define FNC_SWITCHES_END 55
#define FNC_RTRIPS_START 56
#define FNC_RTRIPS_END 80
#define FNC_ETRIPS_START 81
#define FNC_ETRIPS_END 105
#define FNC_SPRITES_START 106
#define FNC_SPRITES_END 115
#define FNC_MTRIGGERS_START 116
#define FNC_MTRIGGERS_END 365
#define FNC_NONE 30000

// COUNTS
#define UPS_COUNT (FNC_UPS_END - FNC_UPS_START + 1)
#define WARPS_COUNT (FNC_WARPS_END - FNC_WARPS_START + 1)
#define SWITCHES_COUNT (FNC_SWITCHES_END - FNC_SWITCHES_START + 1)
#define RTRIPS_COUNT (FNC_RTRIPS_END - FNC_RTRIPS_START + 1)
#define ETRIPS_COUNT (FNC_ETRIPS_END - FNC_ETRIPS_START + 1)
#define SPRITES_COUNT (FNC_SPRITES_END - FNC_SPRITES_START + 1)
#define MTRIGGERS_COUNT (FNC_MTRIGGERS_END - FNC_MTRIGGERS_START + 1)
#define MTAGS_COUNT SPRITES_COUNT
#define GAME_COUNT 4
#define LEVEL_COUNT 10

// KEYS
#define KEY_RETURN 13
#define KEY_ESCAPE 27
#define KEY_SPACE 32
#define KEY_ALT_W 17
#define KEY_ALT_E 18
#define KEY_ALT_R 19
#define KEY_ALT_T 20
#define KEY_ALT_U 22
#define KEY_ALT_S 31
#define KEY_ALT_Z 44
#define KEY_ALT_B 48
#define KEY_ALT_M 50
#define KEY_F1 59
#define KEY_F2 60
#define KEY_F3 61
#define KEY_F4 62
#define KEY_F5 63
#define KEY_F6 64
#define KEY_F7 65
#define KEY_F8 66
#define KEY_F9 67
#define KEY_F10 68
#define KEY_HOME 71
#define KEY_UP 72
#define KEY_PGUP 73
#define KEY_LEFT 75
#define KEY_RIGHT 77
#define KEY_END 79
#define KEY_DOWN 80
#define KEY_PGDN 81
#define KEY_INSERT 82
#define KEY_DELETE 83

#endif